#!/bin/sh

# Get the version number from master.
get_remote_version() {
    version
    version=$(curl -s https://raw.githubusercontent.com/cogwizzle/bash-test/master/bash-test.sh | grep -oP '(?<=# )\d+\.\d+\.\d+')
    echo "$version"
}

# Get the version number from the current branch.
get_local_version() {
    version
    version=$(grep -oP '(?<=# )\d+\.\d+\.\d+' bash-test.sh)
    echo "$version"
}

remote_version=$(get_remote_version)
local_version=$(get_local_version)

# If the versions are the same then exit.
if [ "$remote_version" -eq "$local_version" ]; then
    echo "Update the version number in bash-test.sh"
    exit 1
fi

exit 0
